[package]
name = "mystore"
version = "0.1.0"
authors = ["werner <werner_a_e@yahoo.es>"]
edition = "2018"

[dependencies]
actix-web = "0.7"
diesel = { version = "1.0.0", features = ["postgres"] }
dotenv = "0.9.0"